<div class="container">
	<div class="container__mentions-legales">
		<h2>Mentions légales</h2>
		<p>Vous êtes actuellement connecté au site internet MissionParis.fr édité par Groupe Paris Web Media auquel vous
			pouvez avoir accès via le site www.pariswebmedia.com</p>
		<h3>ARTICLE 1 : INFORMATIONS LEGALES</h3>
		<h4>PERSONNE MORALE :</h4>
		<p>Groupe Paris Web Media</p>
		<h4>EDITEUR :</h4>
		<p>Groupe Paris Web Media</p>
		<h4>REPRESENTANT LEGAL :</h4>
		<p>Laetitia SCHNEIDER</p>
		<h4>DIRECTEUR DE LA PUBLICATION :</h4>
		<p>Laetitia SCHNEIDER</p>
		<h4>HEBERGEMENT :</h4>
		<p>Ce site est hébergé par GO DADDY</p>
		<h4>CONTACT</h4>
		<p>Pour toutes questions relatives à la diffusion des contenus du Site : contact@missionparis.fr</p>
		<h3>ARTICLE 2 : PROPRIETE INTELLECTUELLE</h3>
		<p>Le Site Web et chacun des éléments qui le compose, et notamment les textes, articles, lettres d’informations,
			communiqués, présentations, brochures, illustrations, photographies, programmes informatiques, animations, etc.,
			sont la propriété intellectuelle exclusive du Groupe Paris Web Media et du site missionparis.fr.
			Les Utilisateurs ne sont autorisés qu’à représenter le Site Web sur l’écran de leur ordinateur personnel,
			imprimer
			les pages du Site Web pour leur usage personnel et reproduire temporairement les fichiers qui le constituent
			dans la
			mémoire cache de cet ordinateur aux seules fins de faciliter la consultation du Site Web.</p>
		<p>En particulier et sous réserve des dispositions de l’alinéa précédent, l’Utilisateur n’est pas autorisé à
			reproduire, représenter, modifier, traduire et/ou adapter, partiellement ou totalement, à titre onéreux ou
			gratuit,
			le Site Web et chacun des éléments qui le compose, et reproduire et/ou représenter de telles traductions,
			adaptations et modifications, partiellement ou totalement, à titre onéreux ou gratuit, sans l’accord préalable
			écrit
			de missionparis.fr et du groupe Paris Web Media.</p>
		<h4>CREDIT MARQUES :</h4>
		<p>Titulaire des marques : Paris Web Media</p>
		<h4>REALISATION DU SITE :</h4>
		<p>Développement web : Paris Web Media</p>
		<p>Design graphique : Paris Web Media</p>
		<p>Web Agency : Paris Web Media</p>
		<h3>ARTICLE 3 : COLLECTE DES DONNEES PERSONNELLES</h3>
		<p>Les données personnelles que nous pourrions être amenés à recueillir sont exclusivement destinées au Groupe La
			Dépêche pour vous permettre de profiter des Services offerts par le Site.</p>
		<p>En application des dispositions obligatoires prévues par le RGPD en son article 13, vous pouvez demander la
			communication de vos Données Personnelles et exiger qu’elles soient, selon les cas, rectifiées, complétées,
			mises à
			jour, verrouillées ou effacées, ainsi que de celles qui sont inexactes, incomplètes, équivoques, périmées, ou
			dont
			la collecte, l’utilisation, la communication ou la conservation est interdite.</p>
		<p>Pour cela veuillez contacter notre délégué à la protection des données relatif aux données personnelles qui sont
			collectées sur Groupe La Dépêche, à l’adresse suivante contact@missionparis.fr.</p>
		<p>Pour plus d’information sur les données personnelles, consultez notre Charte sur les Données Personnelles.</p>
		<p>Pour plus d’informations sur les cookies, consultez notre Charte sur les cookies.</p>
		<h4>MISE A JOUR :</h4>
		<p>Mission Paris se réserve le droit de mettre à jour la présente notice légale à tout moment. Mission Paris invite
			donc les utilisateurs à visiter cette page lors de chaque consultation du site afin d’en prendre connaissance.
		</p>
		<h3>Cookies</h3>
		<p>Nous utilisons le strict minimum de cookies sur notre site, et uniquement pour un usage interne. Nous ne vous demandons vos coordonnées uniquement lors de l'envoi d'un formulaire de contact, et uniquement dans le but de vous répondre.</p>
		<p>Dernière mise à jour : 12 décembre 2019</p>
	</div>
</div>